## 00.Pytorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

they are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

In [ ]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5278, 0.4124, 0.0835, 0.8568],
        [0.1467, 0.2769, 0.7961, 0.3066],
        [0.9055, 0.1040, 0.9031, 0.1173]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(224, 224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

# ZEROS AND ONES

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## Creating a range of tensors and tensor-like

In [ ]:
one_ten = torch.arange(0,10)
one_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(start=0, end=11, step=2)

tensor([ 0,  2,  4,  6,  8, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tenor = float_32_tensor.type(torch.float16)
float_16_tenor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tenor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
#

## Getting information from tensors
1. Tensors not right datatypes - to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor , can use tensor.shape
3. Tensors not on the right device - to get device from  a tensor , can use tensor.device

In [ ]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4362, 0.8571, 0.7610, 0.7332],
        [0.2091, 0.2319, 0.3295, 0.9745],
        [0.6813, 0.4644, 0.9987, 0.3074]])

In [ ]:
# some details
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4362, 0.8571, 0.7610, 0.7332],
        [0.2091, 0.2319, 0.3295, 0.9745],
        [0.6813, 0.4644, 0.9987, 0.3074]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### manipulating tensors (tensor operations)
1. addition
2. subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [ ]:
# create a tensor
tensor = torch.tensor([1,2,3,4])
tensor + 11

tensor([12, 13, 14, 15])

In [ ]:
tensor * 10

tensor([10, 20, 30, 40])

In [ ]:
# in-built pyTorch function
add = torch.add(tensor,10)
add

tensor([11, 12, 13, 14])

### Matrix Multiplication

two main ways of performing multiplication in neural networks and deep learning:
1. element-wise
2. matrix multiplication

In [ ]:
# element-wise
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3, 4]) * tensor([1, 2, 3, 4])
Equals: tensor([ 1,  4,  9, 16])


In [ ]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(30)

### One of the most common errors in deep learning : Shape Errors

In [ ]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issue, we can manipulate the shape of our tensors using transpose

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min,max,sum,etc(tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the mean
mean = torch.mean(x.type(torch.float32))
mean

tensor(45.)

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

In [ ]:
import torch
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x_reshaped = x.reshape(1,9)  # adds single dimension
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x (because a view of tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# squeeze = removes single dimension from a target tensor
x = torch.zeros(2,1,2,1,2)
x.size()
x.squeeze()

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [ ]:
x.unsqueeze(dim=0)

tensor([[[[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]]]])

In [ ]:
# permute - rearranges the dimensions a targetted tensor is specified order
x_original = torch.rand(size=(224,224,3)) #[height,width, color_channels]
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0
x_original.shape, x_permuted.shape # [color_channels, height,width]

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Indexing (selecting data from tensors)

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
# index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# all from target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
# all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
# index 0 of 0th and 1st dimension and all of values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

## Pytorch & Numpy

In [ ]:
import numpy as np
array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [ ]:
torch.arange(1.0,10.0).dtype

torch.float32

In [ ]:
# change the value of array, what will this do to 'tensor'
array = array + 1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [ ]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproductibility (trying to take random out of random)
Concept of 'random seed'

In [ ]:
import torch
# random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9156, 0.7726, 0.9294, 0.0129],
        [0.8148, 0.0591, 0.9291, 0.6458],
        [0.1434, 0.8046, 0.7256, 0.9305]])
tensor([[0.2281, 0.9711, 0.9632, 0.4747],
        [0.4712, 0.7730, 0.8915, 0.8500],
        [0.4383, 0.2737, 0.2773, 0.2885]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# set random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

In [ ]:
!nvidia-smi

Thu Jan  9 15:45:21 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

In [ ]:
# putting tensors (and models) on the gpu
tensor = torch.tensor([1,2,3], device='cpu')
# tensor not on gpu
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensors to the gpu
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# moving tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])